### ISSUE TITLE
[Question] Native navigation in Mobile-v2

### ISSUE THREAD

**Issue by xaksis** [jlooper/elocute#2]
Hi @jlooper, I have been trying to make vue-router work with my nativescript-vue app but there are some issues that I am unable to resolve (for example, the back button on Android goes back to the previous screen but doesn't change the route path). I noticed that for elocute mobile-v2 you switched to navigateTo instead of the router. Would you suggest moving away from the router?

**Comment by jlooper** [comment]
Yes, I had to.., manual routing seems much more stable for my use case
