### ISSUE TITLE
navigateTo is not a function

### ISSUE THREAD

**Issue by sivabudati** [jlooper/elocute#6]
After **npm install**, I tried to run mobile-v2 for android with **tns run android --bundle**. After syncing the app on the emulator, I see an error. Relevant part below. I created a different app from the scratch and was able to use manual routing - no issues there. Do I need to do anything with Webpack configuration before I can run?

`JS: 'LoginOrSignup mounted'
JS: 'firebase.init done'
JS: 'Logged out from firebase (init\'s onAuthStateChanged callback)'
12-25 10:04:26.008  3975  3975 E AndroidRuntime: 	at com.tns.Runtime.callJSMethodNative(Native Method)
12-25 10:04:26.008  3975  3975 E AndroidRuntime: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
12-25 10:04:26.008  3975  3975 E AndroidRuntime: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
12-25 10:04:26.008  3975  3975 E AndroidRuntime: 	at com.tns.Runtime.callJSMethod(Runtime.java:983)
12-25 10:04:26.008  3975  3975 E AndroidRuntime: 	at com.tns.Runtime.callJSMethod(Runtime.java:967)
12-25 10:04:26.008  3975  3975 E AndroidRuntime: 	at com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err: com.tns.NativeScriptException: 
System.err: Calling js method onAuthStateChanged failed
System.err: 
System.err: TypeError: nativescript_vue__WEBPACK_IMPORTED_MODULE_0___default.a.navigateTo is not a function
System.err: File: "file:///data/data/com.ladeezfirstmedia.elocute/files/app/bundle.js, line: 1920, column: 62
System.err: 
`

**Comment by Jonarod** [comment]
Same here...

**Comment by lochawala** [comment]
facing same issue..

**Comment by KaelanRichards** [comment]
Any luck on this?
